services:
  backend:
    build: ./backend
    volumes:
      - backend_data:/app/socrates_comparison/cache
    logging:
      driver: journald

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: journald
    depends_on:
      - backend

volumes:
  backend_data:
